
EVALUATE
{
VAR Compound = 
    DaxLib.SVG.Compound.Area(
        SELECTEDVALUE( x[x], 0 ), // x
        SELECTEDVALUE( y[y], 0 ), // y
        SELECTEDVALUE( Width[Width], 100 ), // width
        SELECTEDVALUE( Height[Height], 20), // height
        Dates[Date],    // axisRef
        [Total Cost],   // measureRef
        DaxLib.SVG.Color.Theme(
            MAX( Theme[Theme] ),
            MIN( Variant[Variant] )
        ),              // fillColor
        DaxLib.SVG.Color.Theme(
            MAX( Theme[Theme] ),
            MIN( Variant[Variant] )
        ),              // strokeColor
        0.05,           // paddingX
        0.02,           // paddingY
        0.2,            // fillOpacity
        DaxLib.SVG.Color.PerformanceTheme(
           "Stoplight",
            "veryBad"
        ),                  // minMarkColor
        DaxLib.SVG.Color.PerformanceTheme(
           "Stoplight",
            "veryGood"
        ),                  // maxMarkColor
        [Axes Toggle],  // showAxis
        8               // axisFontSize
    )
RETURN

    IF(
        NOT ISBLANK( Compound ),
        DaxLib.SVG.SVG(
            SELECTEDVALUE( Width[Width], 100 ), // width
            SELECTEDVALUE( Height[Height], 20), // height
            BLANK(),
            Compound,
            BLANK()
        )
    )
}
	